//PROGRAMA DE VALIDAR ESTOQUE
//O OBJETIVO DO PROGRAMA É DISPONIBILIZAR UMA FUNÇÃO VALIDARPRODUTOS QUE RECEBE UMA LISTA DE PRODUTOS(STRING) E VERIFICA SE TODOS OS ITENS NA LISTA EXISTEM NO ESTOQUE(TAMBÉM UMA LISTA DE STRINGS).
//CASO TODOS OS ITENS ESTEJAM DISPONIVEIS EM ESTOQUE DEVE PRINTAR NO CONSOLE A STRING "TODOS OS ITENS DISPONIVEIS"
//CASO NÃO EXISTA UM OU MAIS ITENS DEVE PRINTAR NO CONSOLE "OS ITENS A SEGUIR NAO ESTAO DISPONIVEIS" E PRINTAR NOVAMENTE NO CONSOLE UMA LISTA COM O OS ITENS QUE NAO ESTAO DISPONIVEIS

const estoque = ['uva', 'leite', 'sabao', 'granola', 'iogurte']

function validarProdutos(produtos) {
    console.log(produtos)
}

function verificarEstoque() {
    console.log(estoque)
}

verificarEstoque()

export default validarProdutos
